<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net6</TargetFramework>
    <authors>HiQ Finland</authors>
    <copyright>HiQ Finland</copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/CommunityHiQ/Frends.Community.PaymentServices.Nordea</PackageProjectUrl>
    <IncludeSource>true</IncludeSource>
    <PackageTags>Frends</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>1.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="FrendsTaskMetadata.json" Pack="true" PackagePath="/">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
    <PackageReference Include="GenericParsing" Version="1.2.2" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.3" />
  </ItemGroup>

</Project>
